# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170223_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览数'),
        ),
    ]
