# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170224_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, verbose_name='类别')),
                ('url', models.CharField(max_length=50, verbose_name='链接')),
                ('intro', models.CharField(max_length=50, verbose_name='简介')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 3, 11, 12, 51, 35, 316256, tzinfo=utc), verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 12, 51, 35, 301663, tzinfo=utc), verbose_name='发布日期'),
        ),
    ]
