# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170311_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, verbose_name='类别')),
                ('link', models.CharField(max_length=50, verbose_name='链接')),
                ('intro', models.CharField(max_length=50, verbose_name='简介')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 3, 11, 13, 7, 55, 546774, tzinfo=utc), verbose_name='创建时间')),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 13, 7, 55, 534336, tzinfo=utc), verbose_name='发布日期'),
        ),
    ]
